apiVersion: v1
kind: Pod
metadata:
  name: mysecretpod2
spec:
  containers:
  - name: mysecertcont2
    image: redis
    volumeMounts:
    - name: boo
      mountPath: "/etc/boo"
      readOnly: true
  volumes:
  - name: boo
    secret:
      secretName: mysecret
      optional: false # default setting; "mysecret" must exist
      items:
      - key: username
        path: my-group/my-username
      - key: password
        path: my-group/my-password
