apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  restartPolicy: Always
  containers:
  - name: first-container
    image: ramalaxmi/nginx:4.0
    ports:
    - containerPort: 80
  - name: second-container
    image: ramalaxmi/nginx:5.0
    ports:
    - containerPort: 81
  
