apiVersion: v1
kind: Pod
metadata:
  name:  cm-pod
spec:
  containers:
  - name:  nginx
    image:  nginx
    ports:
    - containerPort:  80
    env:
      - name:  CN_ENV_VAR
        valueFrom:
          configMapkeyRef:
            name:  my-config
            key:  mydata

