apiVersion:  v1
kind:  pod
metadata:  
  name:  simple-cm-app
spec:
  containers:
  - name:  simple-cm-app
    image:  ramalaxmi/env-app:1.0
    ports:
      - containerPort:  8080
    envFrom:
      -configMapRef:
         name:  app-config    
