apiVersion: v1
kind: Pod
metadata:  
  name:  simple-secret-app
spec:
  containers:
  - name:  simple-secret-app
    image:  ramalaxmi/app-secret:1.0
    ports:
      - containerPort:  8080
    envFrom:
      - secretRef:
         name:  app-secret    
